### Análise dos Dados do IDEB (Ensino Médio - 2023)

Este notebook tem como objetivo processar e analisar os dados do IDEB (Índice de Desenvolvimento da Educação Básica) para escolas de ensino médio no Brasil. As etapas incluem:

* **Carregamento dos dados**: Importação do arquivo CSV com informações do IDEB.
* **Limpeza e organização**: Ajuste dos nomes das colunas e preparação dos dados.
* **Filtragem por estado**: Seleção das escolas do estado de São Paulo (SP) para análise.
* **Visualização inicial**: Exibição de amostras dos dados processados.

O foco está em estruturar os dados de forma eficiente para análises futuras, mantendo a transparência e clareza no processo de manipulação.

In [ ]:
# Importa a biblioteca pandas para manipulação de dados
import pandas as pd

In [97]:
# Carrega as linhas de interesse do arquivo CSV
data_ideb = pd.read_csv(
    'divulgacao_ensino_medio_escolas_2023.csv',  # Arquivo de dados
    encoding='ISO-8859-1',  # Codificação do arquivo
    sep=';',  # Separador de colunas
    low_memory=False,  # Reduz avisos sobre tipos mistos
    skiprows=9,  # Ignora as 9 primeiras linhas
    nrows=21587 - 9  # Lê até a linha 21587
)

In [98]:
# Exibe as primeiras 5 linhas do DataFrame para visualização
data_ideb.head()

,SG_UF,CO_MUNICIPIO,NO_MUNICIPIO,ID_ESCOLA,NO_ESCOLA,REDE,VL_APROVACAO_2017_SI_4,VL_APROVACAO_2017_1,VL_APROVACAO_2017_2,VL_APROVACAO_2017_3,...,VL_OBSERVADO_2021,VL_OBSERVADO_2023,VL_PROJECAO_2019,VL_PROJECAO_2021,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53
0,RO,1100015,Alta Floresta D'Oeste,11024682,EEEFM EURIDICE LOPES PEDROSO,Estadual,-,-,-,-,...,"3,6","4,0",-,-,NaN,NaN,NaN,NaN,NaN,NaN
1,RO,1100015,Alta Floresta D'Oeste,11024968,EEEMTI JUSCELINO KUBITSCHEK DE OLIVEIRA,Estadual,"96,1","96,2","95,1","96,4",...,"5,4","5,4","5,2","5,4",NaN,NaN,NaN,NaN,NaN,NaN
2,RO,1100015,Alta Floresta D'Oeste,11025638,COLEGIO TIRADENTES DA POLICIA MILITAR - CTPM XI,Estadual,"85,1","80,2","89,0","87,8",...,-,"4,9","3,6","3,8",NaN,NaN,NaN,NaN,NaN,NaN
3,RO,1100023,Ariquemes,11006773,EEEFM CORA CORALINA,Estadual,-,-,-,-,...,"2,8","2,4",-,-,NaN,NaN,NaN,NaN,NaN,NaN
4,RO,1100023,Ariquemes,11006889,EEEFM ANISIO TEIXEIRA,Estadual,"70,2","62,8","68,8","86,3",...,-,"3,8","3,3","3,5",NaN,NaN,NaN,NaN,NaN,NaN

In [99]:
# Limpar os nomes das colunas
data_ideb.columns = (
    data_ideb.columns
    .str.replace("\n", " ")  # Substituir quebras de linha por espaços
    .str.replace(r"\s+", " ", regex=True)  # Substituir múltiplos espaços por um único espaço
    .str.strip()  # Remover espaços extras no início e fim
)

# Exibir os novos nomes das colunas
data_ideb.columns

Index(['SG_UF', 'CO_MUNICIPIO', 'NO_MUNICIPIO', 'ID_ESCOLA', 'NO_ESCOLA',
       'REDE', 'VL_APROVACAO_2017_SI_4', 'VL_APROVACAO_2017_1',
       'VL_APROVACAO_2017_2', 'VL_APROVACAO_2017_3', 'VL_APROVACAO_2017_4',
       'VL_INDICADOR_REND_2017', 'VL_APROVACAO_2019_SI_4',
       'VL_APROVACAO_2019_1', 'VL_APROVACAO_2019_2', 'VL_APROVACAO_2019_3',
       'VL_APROVACAO_2019_4', 'VL_INDICADOR_REND_2019',
       'VL_APROVACAO_2021_SI_4', 'VL_APROVACAO_2021_1', 'VL_APROVACAO_2021_2',
       'VL_APROVACAO_2021_3', 'VL_APROVACAO_2021_4', 'VL_INDICADOR_REND_2021',
       'VL_APROVACAO_2023_SI_4', 'VL_APROVACAO_2023_1', 'VL_APROVACAO_2023_2',
       'VL_APROVACAO_2023_3', 'VL_APROVACAO_2023_4', 'VL_INDICADOR_REND_2023',
       'VL_NOTA_MATEMATICA_2017', 'VL_NOTA_PORTUGUES_2017',
       'VL_NOTA_MEDIA_2017', 'VL_NOTA_MATEMATICA_2019',
       'VL_NOTA_PORTUGUES_2019', 'VL_NOTA_MEDIA_2019',
       'VL_NOTA_MATEMATICA_2021', 'VL_NOTA_PORTUGUES_2021',
       'VL_NOTA_MEDIA_2021', 'VL_NOTA_MATEMATICA_2023',
       'VL_NOTA_PORTUGUES_2023', 'VL_NOTA_MEDIA_2023', 'VL_OBSERVADO_2017',
       'VL_OBSERVADO_2019', 'VL_OBSERVADO_2021', 'VL_OBSERVADO_2023',
       'VL_PROJECAO_2019', 'VL_PROJECAO_2021', 'Unnamed: 48', 'Unnamed: 49',
       'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53'],
      dtype='object')

In [100]:
# Filtrar apenas as colunas desejadas
colunas_desejadas = ["SG_UF", "CO_MUNICIPIO", "NO_MUNICIPIO", "ID_ESCOLA", "VL_OBSERVADO_2023"]
data_ideb_filtrados = data_ideb[colunas_desejadas].copy()

In [101]:
# Filtra os dados para incluir apenas registros do estado de São Paulo (SP)
data_ideb_filtrados_sp = data_ideb_filtrados[data_ideb_filtrados['SG_UF'] == 'SP']

In [102]:
# Exibe as primeiras 5 linhas dos dados filtrados para São Paulo
data_ideb_filtrados_sp.head()

      SG_UF  CO_MUNICIPIO NO_MUNICIPIO  ID_ESCOLA VL_OBSERVADO_2023
11860    SP       3500105   Adamantina   35030806               4,0
11861    SP       3500105   Adamantina   35031045                 -
11862    SP       3500105   Adamantina   35031082               5,3
11863    SP       3500105   Adamantina   35031100               4,1
11864    SP       3500105   Adamantina   35031112               4,6

In [ ]:
# Exportar o DataFrame para um arquivo CSV
data_ideb_filtrados_sp.to_csv("data_ideb_filtrados_sp.csv", index=False, encoding="utf-8")

# Mensagem de confirmação
print("Arquivo 'data_ideb_filtrados_sp.csv' exportado com sucesso!")

Arquivo 'data_ideb_filtrados_sp.csv' exportado com sucesso!