In [1]:
import pandas as pd
from functools import reduce

In [2]:
df = pd.read_csv(
    "microdados_ed_basica_2023.csv", encoding="ISO-8859-1", sep=";", low_memory=False
)

In [3]:
df.columns

Index(['NU_ANO_CENSO', 'NO_REGIAO', 'CO_REGIAO', 'NO_UF', 'SG_UF', 'CO_UF',
       'NO_MUNICIPIO', 'CO_MUNICIPIO', 'NO_REGIAO_GEOG_INTERM',
       'CO_REGIAO_GEOG_INTERM',
       ...
       'QT_TUR_BAS_D', 'QT_TUR_BAS_N', 'QT_TUR_BAS_EAD', 'QT_TUR_INF_INT',
       'QT_TUR_INF_CRE_INT', 'QT_TUR_INF_PRE_INT', 'QT_TUR_FUND_INT',
       'QT_TUR_FUND_AI_INT', 'QT_TUR_FUND_AF_INT', 'QT_TUR_MED_INT'],
      dtype='object', length=408)

In [4]:
df1 = df[["CO_ENTIDADE", "TP_DEPENDENCIA"]]

In [5]:
# Lista para armazenar os valores
dependencia = []

# Iterar pelas linhas do DataFrame
for _, row in df1.iterrows():
    if row["TP_DEPENDENCIA"] == 1:
        dependencia.append("Federal")
    elif row["TP_DEPENDENCIA"] == 2:
        dependencia.append("Estadual")
    elif row["TP_DEPENDENCIA"] == 3:
        dependencia.append("Municipal")
    else:
        dependencia.append("Privada")

# Adicionar a nova coluna ao DataFrame
df1["DEPENDENCIA"] = dependencia

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\694928164.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1["DEPENDENCIA"] = dependencia

In [6]:
df1 = df1.drop(["TP_DEPENDENCIA"], axis=1)

In [7]:
df1.to_csv("estadual_municipal_privada.csv", index=False)

In [8]:
df2 = df[["NO_ENTIDADE", "CO_ENTIDADE", "TP_SITUACAO_FUNCIONAMENTO"]]

In [9]:
# Lista para armazenar os valores
atividade = []

# Iterar pelas linhas do DataFrame
for _, row in df2.iterrows():
    if row["TP_SITUACAO_FUNCIONAMENTO"] == 1:
        atividade.append("Em atividade")
    elif row["TP_SITUACAO_FUNCIONAMENTO"] == 2:
        atividade.append("Paralisada")
    else:
        atividade.append("Extinta")

# Adicionar a nova coluna ao DataFrame
df2["ATIVIDADE"] = atividade

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\3832035466.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["ATIVIDADE"] = atividade

In [10]:
df2 = df2.drop(["TP_SITUACAO_FUNCIONAMENTO"], axis=1)

In [11]:
df2.to_csv("atividade_paralisada_extinta.csv", index=False)

In [12]:
df3 = df[
    [
        "NO_ENTIDADE",
        "CO_ENTIDADE",
        "IN_VINCULO_SECRETARIA_EDUCACAO",
        "IN_VINCULO_SEGURANCA_PUBLICA",
        "IN_VINCULO_SECRETARIA_SAUDE",
        "IN_VINCULO_OUTRO_ORGAO",
    ]
]

In [13]:
df3["IN_VINCULO_SEGURANCA_PUBLICA"].unique()

array([ 0., nan,  1.])

In [14]:
df3["IN_VINCULO_SECRETARIA_SAUDE"].unique()

array([ 0., nan,  1.])

In [15]:
df3["IN_VINCULO_OUTRO_ORGAO"].unique()

array([ 0., nan,  1.])

In [16]:
# Lista para armazenar os valores
vinculo = []

# Iterar pelas linhas do DataFrame
for _, row in df3.iterrows():
    if row["IN_VINCULO_SEGURANCA_PUBLICA"] == 1.0:
        vinculo.append("Órgão de Segurança Pública")
    elif row["IN_VINCULO_SECRETARIA_SAUDE"] == 1.0:
        vinculo.append("Secretaria de Saúde")
    elif row["IN_VINCULO_SECRETARIA_EDUCACAO"] == 1.0:
        vinculo.append("Secretaria de Educação")
    elif row["IN_VINCULO_OUTRO_ORGAO"] == 1.0:
        vinculo.append("Outro Órgão Público")
    else:
        vinculo.append("Não")

# Adicionar a nova coluna ao DataFrame
df3["VÍNCULOS_PUBLICOS"] = vinculo

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\1249707319.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df3["VÍNCULOS_PUBLICOS"] = vinculo

In [17]:
df3 = df3.drop(
    [
        "IN_VINCULO_SEGURANCA_PUBLICA",
        "IN_VINCULO_SECRETARIA_EDUCACAO",
        "IN_VINCULO_SECRETARIA_SAUDE",
        "IN_VINCULO_OUTRO_ORGAO",
    ],
    axis=1,
)

In [18]:
df3.to_csv("vinculos_publicos1.csv", index=False)

In [19]:
df4 = df[
    [
        "NO_ENTIDADE",
        "CO_ENTIDADE",
        "IN_MANT_ESCOLA_PRIVADA_EMP",
        "IN_MANT_ESCOLA_PRIVADA_ONG",
        "IN_MANT_ESCOLA_PRIVADA_OSCIP",
        "IN_MANT_ESCOLA_PRIV_ONG_OSCIP",
        "IN_MANT_ESCOLA_PRIVADA_SIND",
        "IN_MANT_ESCOLA_PRIVADA_SIST_S",
        "IN_MANT_ESCOLA_PRIVADA_S_FINS",
    ]
]

In [20]:
df4["IN_MANT_ESCOLA_PRIVADA_EMP"].unique()

array([nan,  1.,  0.])

In [21]:
# Lista para armazenar os valores
mantenedor = []

# Iterar pelas linhas do DataFrame
for _, row in df4.iterrows():
    if row["IN_MANT_ESCOLA_PRIVADA_EMP"] == 1.0:
        mantenedor.append("Empresa do setor privado")
    elif row["IN_MANT_ESCOLA_PRIVADA_ONG"] == 1.0:
        mantenedor.append("Organização Não Governamental - ONG")
    elif row["IN_MANT_ESCOLA_PRIVADA_OSCIP"] == 1.0:
        mantenedor.append("Organização da Sociedade Civil de Interesse Público - OSCIP")
    elif row["IN_MANT_ESCOLA_PRIVADA_SIND"] == 1.0:
        mantenedor.append(
            "Sindicatos de trabalhadores ou patronais, associações e cooperativas"
        )
    elif row["IN_MANT_ESCOLA_PRIVADA_SIST_S"] == 1.0:
        mantenedor.append("Sistema S (Sesi, Senai, Sesc, outros)")
    elif row["IN_MANT_ESCOLA_PRIVADA_S_FINS"] == 1.0:
        mantenedor.append("Instituições sem fins lucrativos")
    else:
        mantenedor.append("Empresa do setor privado")

# Adicionar a nova coluna ao DataFrame
df4["MANTENEDOR_ESCOLA_PRIVADA"] = mantenedor

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\3735930546.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4["MANTENEDOR_ESCOLA_PRIVADA"] = mantenedor

In [22]:
df4 = df4.drop(
    [
        "IN_MANT_ESCOLA_PRIVADA_EMP",
        "IN_MANT_ESCOLA_PRIVADA_ONG",
        "IN_MANT_ESCOLA_PRIVADA_OSCIP",
        "IN_MANT_ESCOLA_PRIV_ONG_OSCIP",
        "IN_MANT_ESCOLA_PRIVADA_SIND",
        "IN_MANT_ESCOLA_PRIVADA_SIST_S",
        "IN_MANT_ESCOLA_PRIVADA_S_FINS",
    ],
    axis=1,
)

In [23]:
df4.to_csv("mantenedor_privada.csv", index=False)

In [24]:
df5 = df[["NO_ENTIDADE", "CO_ENTIDADE", "TP_OCUPACAO_PREDIO_ESCOLAR"]]

In [25]:
# Lista para armazenar os valores
predio_escolar = []

# Iterar pelas linhas do DataFrame
for _, row in df5.iterrows():
    if row["TP_OCUPACAO_PREDIO_ESCOLAR"] == 1:
        predio_escolar.append("Próprio")
    elif row["TP_OCUPACAO_PREDIO_ESCOLAR"] == 2:
        predio_escolar.append("Alugado")
    elif row["TP_OCUPACAO_PREDIO_ESCOLAR"] == 3:
        predio_escolar.append("Cedido")
    else:
        predio_escolar.append("Indefinido")

# Adicionar a nova coluna ao DataFrame
df5["PREDIO_ESCOLAR"] = predio_escolar

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\1740080905.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df5["PREDIO_ESCOLAR"] = predio_escolar

In [26]:
df5 = df5.drop(["TP_OCUPACAO_PREDIO_ESCOLAR"], axis=1)

In [27]:
df5.to_csv("predio_escolar.csv", index=False)

In [28]:
df6 = df[
    [
        "NO_ENTIDADE",
        "CO_ENTIDADE",
        "IN_LOCAL_FUNC_SOCIOEDUCATIVO",
        "IN_LOCAL_FUNC_UNID_PRISIONAL",
        "IN_LOCAL_FUNC_PRISIONAL_SOCIO",
        "IN_LOCAL_FUNC_GALPAO",
        "TP_OCUPACAO_GALPAO",
        "IN_LOCAL_FUNC_SALAS_OUTRA_ESC",
        "IN_LOCAL_FUNC_OUTROS",
        "IN_PREDIO_COMPARTILHADO",
    ]
]

In [29]:
# Lista para armazenar os valores
local = []

# Iterar pelas linhas do DataFrame
for _, row in df6.iterrows():
    if row["IN_LOCAL_FUNC_SOCIOEDUCATIVO"] == 1:
        local.append("Unidade de Atendimento socioeducativo")
    elif row["IN_LOCAL_FUNC_UNID_PRISIONAL"] == 1:
        local.append("Unidade Prisional")
    elif row["IN_LOCAL_FUNC_PRISIONAL_SOCIO"] == 1:
        local.append("Unidade de atendimento socioeducativo")
    elif row["IN_LOCAL_FUNC_GALPAO"] == 1:
        local.append("Galpão/Rancho/Paiol/Barracão")
    elif row["IN_LOCAL_FUNC_SALAS_OUTRA_ESC"] == 1:
        local.append("Salas em outra escola")
    elif row["IN_PREDIO_COMPARTILHADO"] == 1:
        local.append("Prédio compartilhado com outra escola")
    else:
        local.append("Outros")

# Adicionar a nova coluna ao DataFrame
df6["LOCAL_ESCOLAR"] = local

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\3846497367.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df6["LOCAL_ESCOLAR"] = local

In [30]:
df6 = df6.drop(
    [
        "IN_LOCAL_FUNC_SOCIOEDUCATIVO",
        "IN_LOCAL_FUNC_UNID_PRISIONAL",
        "IN_LOCAL_FUNC_PRISIONAL_SOCIO",
        "IN_LOCAL_FUNC_GALPAO",
        "TP_OCUPACAO_GALPAO",
        "IN_LOCAL_FUNC_SALAS_OUTRA_ESC",
        "IN_LOCAL_FUNC_OUTROS",
        "IN_PREDIO_COMPARTILHADO",
    ],
    axis=1,
)

In [31]:
df6.to_csv("local_do_predio_escolar.csv", index=False)

In [32]:
df7 = df[
    [
        "NO_ENTIDADE",
        "CO_ENTIDADE",
        "IN_AGUA_POTAVEL",
        "IN_AGUA_REDE_PUBLICA",
        "IN_AGUA_POCO_ARTESIANO",
        "IN_AGUA_CACIMBA",
        "IN_AGUA_FONTE_RIO",
        "IN_AGUA_INEXISTENTE",
    ]
]

In [33]:
# Lista para armazenar os valores
agua = []

# Iterar pelas linhas do DataFrame
for _, row in df7.iterrows():
    if row["IN_AGUA_FONTE_RIO"] == 1:
        agua.append("Fonte/Rio/Igarapé/Riacho/Córrego")
    elif row["IN_AGUA_REDE_PUBLICA"] == 1:
        agua.append("Rede pública")
    elif row["IN_AGUA_POCO_ARTESIANO"] == 1:
        agua.append("Poço artesiano")
    elif row["IN_AGUA_CACIMBA"] == 1:
        agua.append("Cacimba/Cisterna/Poço")
    else:
        agua.append("Não há abastecimento de água")

# Adicionar a nova coluna ao DataFrame
df7["ABASTECIMENTO_AGUA"] = agua

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\2419081158.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df7["ABASTECIMENTO_AGUA"] = agua

In [34]:
df7 = df7.drop(
    [
        "IN_AGUA_POTAVEL",
        "IN_AGUA_REDE_PUBLICA",
        "IN_AGUA_POCO_ARTESIANO",
        "IN_AGUA_POCO_ARTESIANO",
        "IN_AGUA_FONTE_RIO",
        "IN_AGUA_INEXISTENTE",
        "IN_AGUA_CACIMBA",
    ],
    axis=1,
)

In [35]:
df7.to_csv("abastecimento_de_agua.csv", index=False)

In [36]:
df8 = df[
    [
        "NO_ENTIDADE",
        "CO_ENTIDADE",
        "IN_ENERGIA_REDE_PUBLICA",
        "IN_ENERGIA_GERADOR_FOSSIL",
        "IN_ENERGIA_RENOVAVEL",
        "IN_ENERGIA_INEXISTENTE",
    ]
]

In [37]:
# Lista para armazenar os valores
energia = []

# Iterar pelas linhas do DataFrame
for _, row in df8.iterrows():
    if row["IN_ENERGIA_REDE_PUBLICA"] == 1:
        energia.append("Rede pública")
    elif row["IN_ENERGIA_GERADOR_FOSSIL"] == 1:
        energia.append("Gerador movido a combustível fóssil")
    elif row["IN_ENERGIA_RENOVAVEL"] == 1:
        energia.append(
            "Fontes de energia renováveis ou alternativas (gerador a biocombustível e/ou biodigestores, eólica, solar, outras)"
        )
    else:
        energia.append("Não há energia elétrica")

# Adicionar a nova coluna ao DataFrame
df8["ABASTECIMENTO_ENERGIA"] = energia

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\1929605048.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df8["ABASTECIMENTO_ENERGIA"] = energia

In [38]:
df8 = df8.drop(
    [
        "IN_ENERGIA_REDE_PUBLICA",
        "IN_ENERGIA_GERADOR_FOSSIL",
        "IN_ENERGIA_RENOVAVEL",
        "IN_ENERGIA_INEXISTENTE",
    ],
    axis=1,
)

In [39]:
df8.to_csv("abastecimento_de_energia.csv", index=False)

In [40]:
df9 = df[
    [
        "NO_ENTIDADE",
        "CO_ENTIDADE",
        "IN_ACESSIBILIDADE_CORRIMAO",
        "IN_ACESSIBILIDADE_ELEVADOR",
        "IN_ACESSIBILIDADE_PISOS_TATEIS",
        "IN_ACESSIBILIDADE_VAO_LIVRE",
        "IN_ACESSIBILIDADE_RAMPAS",
        "IN_ACESSIBILIDADE_SINAL_SONORO",
        "IN_ACESSIBILIDADE_SINAL_TATIL",
        "IN_ACESSIBILIDADE_SINAL_VISUAL",
        "IN_ACESSIBILIDADE_INEXISTENTE",
    ]
]

In [41]:
# Lista para armazenar os valores
soma_acessibilidade = []

# Iterar pelas linhas do DataFrame
for _, row in df9.iterrows():
    acessibilidade = 0
    if row["IN_ACESSIBILIDADE_CORRIMAO"] == 1:
        acessibilidade += 1
    if row["IN_ACESSIBILIDADE_ELEVADOR"] == 1:
        acessibilidade += 1
    if row["IN_ACESSIBILIDADE_PISOS_TATEIS"] == 1:
        acessibilidade += 1
    if row["IN_ACESSIBILIDADE_VAO_LIVRE"] == 1:
        acessibilidade += 1
    if row["IN_ACESSIBILIDADE_RAMPAS"] == 1:
        acessibilidade += 1
    if row["IN_ACESSIBILIDADE_SINAL_SONORO"] == 1:
        acessibilidade += 1
    if row["IN_ACESSIBILIDADE_SINAL_TATIL"] == 1:
        acessibilidade += 1
    if row["IN_ACESSIBILIDADE_SINAL_VISUAL"] == 1:
        acessibilidade += 1

    soma_acessibilidade.append(acessibilidade)

# Adicionar a nova coluna ao DataFrame
df9["TAXA_DE_ACESSIBILIDADE"] = soma_acessibilidade

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\4291360322.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df9["TAXA_DE_ACESSIBILIDADE"] = soma_acessibilidade

In [42]:
df9 = df9.drop(
    [
        "IN_ACESSIBILIDADE_CORRIMAO",
        "IN_ACESSIBILIDADE_ELEVADOR",
        "IN_ACESSIBILIDADE_PISOS_TATEIS",
        "IN_ACESSIBILIDADE_VAO_LIVRE",
        "IN_ACESSIBILIDADE_RAMPAS",
        "IN_ACESSIBILIDADE_SINAL_SONORO",
        "IN_ACESSIBILIDADE_SINAL_TATIL",
        "IN_ACESSIBILIDADE_SINAL_VISUAL",
        "IN_ACESSIBILIDADE_INEXISTENTE",
    ],
    axis=1,
)

In [43]:
df9.to_csv("taxa_de_acesibilidade.csv", index=False)

In [44]:
df10 = df[
    [
        "NO_ENTIDADE",
        "CO_ENTIDADE",
        "DS_ENDERECO",
        "NU_ENDERECO",
        "DS_COMPLEMENTO",
        "NO_BAIRRO",
        "CO_CEP",
        "NU_DDD",
        "NU_TELEFONE",
    ]
]

In [45]:
df10.to_csv("endereços_e_contato.csv", index=False)

In [46]:
# Função para combinar todos os DataFrames com base na coluna 'CO_ENTIDADE'
dfs = [df2, df3, df4, df5, df6, df7, df8, df9, df10]
# Merge ignorando a coluna "NO_ENTIDADE"
df_merged1 = reduce(
    lambda left, right: pd.merge(
        left.drop(columns=["NO_ENTIDADE"], errors="ignore"),
        right.drop(columns=["NO_ENTIDADE"], errors="ignore"),
        on="CO_ENTIDADE",
    ),
    dfs,
)

In [47]:
df_names = df[
    [
        "NO_MUNICIPIO",
        "NO_UF",
        "SG_UF",
        "CO_DISTRITO",
        "NO_ENTIDADE",
        "CO_ENTIDADE",
    ]
]

In [48]:
df_merged0 = pd.merge(df11, df_merged1, on="CO_ENTIDADE", how="left")

NameError: name 'df11' is not defined

In [49]:
df_merged0.to_csv("merged_incompleto1.csv", index=False)

NameError: name 'df_merged0' is not defined

In [ ]:
df_merged0.to_json(
    "merged_incompleto0.json", orient="records", lines=True, force_ascii=False, indent=4
)

In [51]:
df12 = df[
    [
        "CO_ENTIDADE",
        "IN_ESGOTO_REDE_PUBLICA",
        "IN_ESGOTO_FOSSA_SEPTICA",
        "IN_ESGOTO_FOSSA_COMUM",
        "IN_ESGOTO_FOSSA",
        "IN_ESGOTO_INEXISTENTE",
    ]
]

In [52]:
# Lista para armazenar os valores
esgoto = []

# Iterar pelas linhas do DataFrame
for _, row in df12.iterrows():
    if row["IN_ESGOTO_REDE_PUBLICA"] == 1:
        esgoto.append("Rede pública")
    elif row["IN_ESGOTO_FOSSA_SEPTICA"] == 1:
        esgoto.append("Fossa Séptica")
    elif row["IN_ESGOTO_FOSSA_COMUM"] == 1:
        esgoto.append("Fossa comum")
    elif row["IN_ESGOTO_FOSSA"] == 1:
        esgoto.append("Fossa comum")
    else:
        esgoto.append("Não há tratamento de esgoto")

# Adicionar a nova coluna ao DataFrame
df12["ESGOTO"] = esgoto

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\1942153091.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df12["ESGOTO"] = esgoto

In [53]:
df12 = df12.drop(
    [
        "IN_ESGOTO_REDE_PUBLICA",
        "IN_ESGOTO_FOSSA_SEPTICA",
        "IN_ESGOTO_FOSSA_COMUM",
        "IN_ESGOTO_FOSSA",
        "IN_ESGOTO_INEXISTENTE",
    ],
    axis=1,
)

In [54]:
df12.to_csv("esgoto.csv", index=False)

In [55]:
df13 = df[
    [
        "CO_ENTIDADE",
        "IN_AREA_VERDE",
        "IN_BIBLIOTECA",
        "IN_LABORATORIO_CIENCIAS",
        "IN_LABORATORIO_INFORMATICA",
        "IN_LABORATORIO_EDUC_PROF",
        "IN_PISCINA",
        "IN_QUADRA_ESPORTES",
        "IN_SALA_ATELIE_ARTES",
        "IN_SALA_MUSICA_CORAL",
        "IN_SALA_ESTUDIO_DANCA",
        "IN_SALA_ESTUDIO_GRAVACAO",
        "IN_SALA_OFICINAS_EDUC_PROF",
        "IN_VIVEIRO",
    ]
]

In [56]:
# Lista para armazenar os valores
soma_infraestrutura = []

# Iterar pelas linhas do DataFrame
for _, row in df13.iterrows():
    infraestrutura = 0
    if row["IN_AREA_VERDE"] == 1:
        infraestrutura += 1
    if row["IN_BIBLIOTECA"] == 1:
        infraestrutura += 1
    if row["IN_LABORATORIO_CIENCIAS"] == 1:
        infraestrutura += 1
    if row["IN_LABORATORIO_INFORMATICA"] == 1:
        infraestrutura += 1
    if row["IN_LABORATORIO_EDUC_PROF"] == 1:
        infraestrutura += 1
    if row["IN_PISCINA"] == 1:
        infraestrutura += 1
    if row["IN_QUADRA_ESPORTES"] == 1:
        infraestrutura += 1
    if row["IN_SALA_ATELIE_ARTES"] == 1:
        infraestrutura += 1
    if row["IN_SALA_MUSICA_CORAL"] == 1:
        infraestrutura += 1
    if row["IN_SALA_ESTUDIO_DANCA"] == 1:
        infraestrutura += 1
    if row["IN_SALA_ESTUDIO_GRAVACAO"] == 1:
        infraestrutura += 1
    if row["IN_SALA_OFICINAS_EDUC_PROF"] == 1:
        infraestrutura += 1
    if row["IN_VIVEIRO"] == 1:
        infraestrutura += 1

    soma_infraestrutura.append(infraestrutura)

# Adicionar a nova coluna ao DataFrame
df13["TAXA_DE_INFRAESTRUTURA"] = soma_infraestrutura

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\1225201833.py:37: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13["TAXA_DE_INFRAESTRUTURA"] = soma_infraestrutura

In [57]:
# Dicionário com as infraestruturas e suas representações em string
infraestrutura_dict = {
    "IN_AREA_VERDE": "Área Verde",
    "IN_BIBLIOTECA": "Biblioteca",
    "IN_LABORATORIO_CIENCIAS": "Laboratório de Ciências",
    "IN_LABORATORIO_INFORMATICA": "Laboratório de Informática",
    "IN_LABORATORIO_EDUC_PROF": "Laboratório Educacional Profissional",
    "IN_PISCINA": "Piscina",
    "IN_QUADRA_ESPORTES": "Quadra de Esportes",
    "IN_SALA_ATELIE_ARTES": "Sala de Ateliê de Artes",
    "IN_SALA_MUSICA_CORAL": "Sala de Música e Coral",
    "IN_SALA_ESTUDIO_DANCA": "Sala de Estúdio de Dança",
    "IN_SALA_ESTUDIO_GRAVACAO": "Sala de Estúdio de Gravação",
    "IN_SALA_OFICINAS_EDUC_PROF": "Sala de Oficinas de Educação Profissional",
    "IN_VIVEIRO": "Viveiro/Criação de animais",
}

# Lista para armazenar as listas de infraestruturas
infraestrutura_list = []

# Iterar pelas linhas do DataFrame
for _, row in df13.iterrows():
    infraestrutura = []

    # Verificar cada infraestrutura, e se o valor for 1, adicionar a string correspondente
    for coluna, nome in infraestrutura_dict.items():
        if row[coluna] == 1:
            infraestrutura.append(nome)

    # Adicionar a lista de infraestrutura para o índice correspondente
    infraestrutura_list.append(infraestrutura)

# Adicionar a nova coluna ao DataFrame
df13["LISTA_INFRAESTRUTURAS"] = infraestrutura_list

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\2840983879.py:34: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df13["LISTA_INFRAESTRUTURAS"] = infraestrutura_list

In [58]:
df13 = df13.drop(
    [
        "IN_AREA_VERDE",
        "IN_BIBLIOTECA",
        "IN_LABORATORIO_CIENCIAS",
        "IN_LABORATORIO_INFORMATICA",
        "IN_LABORATORIO_EDUC_PROF",
        "IN_PISCINA",
        "IN_QUADRA_ESPORTES",
        "IN_SALA_ATELIE_ARTES",
        "IN_SALA_MUSICA_CORAL",
        "IN_SALA_ESTUDIO_DANCA",
        "IN_SALA_ESTUDIO_GRAVACAO",
        "IN_SALA_OFICINAS_EDUC_PROF",
        "IN_VIVEIRO",
    ],
    axis=1,
)

In [59]:
df13.to_csv("infraestrutura.csv", index=False)

In [60]:
df14 = df[
    [
        "CO_ENTIDADE",
        "IN_PROF_FONAUDIOLOGO",
        "IN_PROF_NUTRICIONISTA",
        "IN_PROF_PSICOLOGO",
        "IN_PROF_SEGURANCA",
        "IN_PROF_MONITORES",
        "IN_PROF_ASSIST_SOCIAL",
        "IN_PROF_TRAD_LIBRAS",
    ]
]

In [61]:
# Dicionário com as infraestruturas e suas representações em string
profissionais_dict = {
    "IN_PROF_FONAUDIOLOGO": "Fonoaudiólogo",
    "IN_PROF_NUTRICIONISTA": "Nutricionista",
    "IN_PROF_PSICOLOGO": "Psicólogo",
    "IN_PROF_SEGURANCA": "Segurança/Guarda",
    "IN_PROF_MONITORES": "Técnicos de apoio a tecnologias educacionais",
    "IN_PROF_ASSIST_SOCIAL": "Assistência Social",
    "IN_PROF_TRAD_LIBRAS": "Tradutor e intérprete de Libras",
}

# Lista para armazenar as listas de infraestruturas
profissionais_list = []

# Iterar pelas linhas do DataFrame
for _, row in df14.iterrows():
    profissionais = []

    # Verificar cada infraestrutura, e se o valor for 1, adicionar a string correspondente
    for coluna, nome in profissionais_dict.items():
        if row[coluna] == 1:
            profissionais.append(nome)

    # Adicionar a lista de infraestrutura para o índice correspondente
    profissionais_list.append(profissionais)

# Adicionar a nova coluna ao DataFrame
df14["LISTA_PROFISSIONAIS"] = profissionais_list

C:\Users\Georgia Cavallaro\AppData\Local\Temp\ipykernel_12120\2875751202.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df14["LISTA_PROFISSIONAIS"] = profissionais_list

In [62]:
df14 = df14.drop(
    [
        "IN_PROF_FONAUDIOLOGO",
        "IN_PROF_NUTRICIONISTA",
        "IN_PROF_PSICOLOGO",
        "IN_PROF_SEGURANCA",
        "IN_PROF_MONITORES",
        "IN_PROF_ASSIST_SOCIAL",
        "IN_PROF_TRAD_LIBRAS",
    ],
    axis=1,
)

In [63]:
df14.to_csv("corpo_docente.csv", index=False)

In [64]:
# Função para combinar todos os DataFrames com base na coluna 'CO_ENTIDADE'
dfs = [df2, df3, df4, df5, df6, df7, df8, df9, df10, df12, df13, df14]
# Merge ignorando a coluna "NO_ENTIDADE"
df_merged2 = reduce(
    lambda left, right: pd.merge(
        left.drop(columns=["NO_ENTIDADE"], errors="ignore"),
        right.drop(columns=["NO_ENTIDADE"], errors="ignore"),
        on="CO_ENTIDADE",
    ),
    dfs,
)

In [65]:
df_merged_brasil = pd.merge(df_names, df_merged2, on="CO_ENTIDADE", how="left")

In [66]:
df_merged_brasil.to_csv("merged_brasil.csv", index=False)

In [67]:
df_cidade_sao_paulo = df_merged_brasil[df_merged_brasil["NO_MUNICIPIO"] == "São Paulo"]

In [68]:
df_cidade_sao_paulo.to_csv("merged_cidade_sp.csv", index=False)

In [69]:
df_cidade_sao_paulo.to_json(
    "merged_cidade_sp.json", orient="records", lines=True, force_ascii=False, indent=4
)

In [70]:
df_coordenadas = pd.read_csv(
    "dados_coord_geo.csv", encoding="ISO-8859-1", sep=",", low_memory=False
)

In [71]:
# Função para combinar todos os DataFrames com base na coluna 'CO_ENTIDADE'
dfs = [
    df_coordenadas,
    df1,
    df2,
    df3,
    df4,
    df5,
    df6,
    df7,
    df8,
    df9,
    df10,
    df12,
    df13,
    df14,
]
# Merge ignorando a coluna "NO_ENTIDADE"
df_merged3 = reduce(
    lambda left, right: pd.merge(
        left.drop(columns=["NO_ENTIDADE"], errors="ignore"),
        right.drop(columns=["NO_ENTIDADE"], errors="ignore"),
        on="CO_ENTIDADE",
    ),
    dfs,
)

In [72]:
df_merged_brasil = pd.merge(df_names, df_merged3, on="CO_ENTIDADE", how="left")

In [73]:
df_merged_brasil.to_csv("merged_brasil.csv", index=False)

In [83]:
df_merged_brasil

,NO_MUNICIPIO,NO_UF,SG_UF,CO_DISTRITO,NO_ENTIDADE,CO_ENTIDADE,longitude,latitude,DEPENDENCIA,ATIVIDADE,VÍNCULOS_PUBLICOS,MANTENEDOR_ESCOLA_PRIVADA,PREDIO_ESCOLAR,LOCAL_ESCOLAR,ABASTECIMENTO_AGUA,ABASTECIMENTO_ENERGIA,TAXA_DE_ACESSIBILIDADE,DS_ENDERECO,NU_ENDERECO,DS_COMPLEMENTO,NO_BAIRRO,CO_CEP,NU_DDD,NU_TELEFONE,ESGOTO,TAXA_DE_INFRAESTRUTURA,LISTA_INFRAESTRUTURAS,LISTA_PROFISSIONAIS
0,Porto Velho,Rondônia,RO,110020505,EEEE ABNAEL MACHADO DE LIMA - CENE,11000023,-63.854011,-8.758459,Estadual,Em atividade,Secretaria de Educação,Empresa do setor privado,Alugado,Outros,Poço artesiano,Rede pública,0,AVENIDA AMAZONAS,6492,ZONA LESTE,TIRADENTES,76824556,69.0,992222374.0,Rede pública,3,"[Biblioteca, Laboratório de Informática, Sala ...","[Psicólogo, Segurança/Guarda, Técnicos de apoi..."
1,Porto Velho,Rondônia,RO,110020505,EMEIEF PEQUENOS TALENTOS,11000040,-63.883919,-8.793730,Municipal,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Outros,Poço artesiano,Rede pública,3,RUA CAETANO,3256,PREDIO,CALADINHO,76808108,69.0,32274273.0,Rede pública,0,[],[]
2,Porto Velho,Rondônia,RO,110020505,CENTRO DE ENSINO CLASSE A,11000058,NaN,NaN,Privada,Em atividade,Não,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,3,AVENIDA CARLOS GOMES,1135,NaN,CENTRO,76801123,69.0,32244473.0,Rede pública,4,"[Biblioteca, Laboratório de Ciências, Laborató...",[Psicólogo]
3,Porto Velho,Rondônia,RO,110020505,CENTRO EDUCACIONAL PRESBITERIANO 15 DE NOVEMBRO,11000082,NaN,NaN,Privada,Em atividade,Não,Empresa do setor privado,Indefinido,Outros,Rede pública,Rede pública,0,RUA ALMIRANTE BARROSO,1483,NaN,SANTA BARBARA,76804214,69.0,32245636.0,Rede pública,2,"[Biblioteca, Quadra de Esportes]",[]
4,Porto Velho,Rondônia,RO,110020505,CENTRO EDUC CORA CORALINA,11000104,NaN,NaN,Privada,Em atividade,Não,Empresa do setor privado,Próprio,Outros,Poço artesiano,Rede pública,3,RUA MEXICO,1056,NaN,NOVA PORTO VELHO,76820190,69.0,32252616.0,Fossa Séptica,2,"[Biblioteca, Quadra de Esportes]","[Técnicos de apoio a tecnologias educacionais,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217620,Brasília,Distrito Federal,DF,530010805,ESC PEQUENO ENCANTO,53084020,NaN,NaN,Privada,Em atividade,Não,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,8,QUADRA QNO 18 CONJUNTO 7 LOTE,05,NaN,CEILANDIA NORTE CEILANDIA,72260807,61.0,33777738.0,Rede pública,1,[Laboratório de Informática],[]
217621,Brasília,Distrito Federal,DF,530010805,SOCIEDADE ANCHIETA DE EDUCACAO INTEGRAL LTDA,53084039,NaN,NaN,Privada,Em atividade,Não,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,3,QSC 19 QUADRA 27 - CONJUNTO A LOTE 16,NaN,SETOR PRIMAVERA,TAGUATINGA,72017323,61.0,33510110.0,Rede pública,4,"[Área Verde, Biblioteca, Laboratório de Ciênci...","[Nutricionista, Psicólogo, Segurança/Guarda, T..."
217622,Brasília,Distrito Federal,DF,530010805,COL MAPA,53084055,NaN,NaN,Privada,Em atividade,Não,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,3,QUADRA EQNP 15/19 MODULO F,NaN,NaN,CEILANDIA NORTE CEILANDIA,72241576,61.0,33791116.0,Rede pública,4,"[Laboratório de Ciências, Laboratório de Infor...",[]
217623,Brasília,Distrito Federal,DF,530010805,COBIAN - COL BIANGULO,53085000,NaN,NaN,Privada,Em atividade,Não,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,3,QNJ 22 - LOTES 34 E 36,NaN,NaN,TAGUATINGA NORTE,72140220,61.0,34756945.0,Rede pública,5,"[Área Verde, Biblioteca, Laboratório de Ciênci...",[]
217624,Brasília,Distrito Federal,DF,530010805,CED VITORIA REGIA,53086007,NaN,NaN,Privada,Em atividade,Não,Empresa do setor privado,Alugado,Outros,Rede pública,Rede pública,3,RUA 07 CH 333 LOTE 333/E,NaN,NaN,SETOR HABITACIONAL VICENTE PIRES,72007345,61.0,35976668.0,Fossa comum,3,"[Área Verde, Piscina, Quadra de Esportes]",[Assistência Social]

In [74]:
df_estado_sp = df_merged_brasil[df_merged_brasil["SG_UF"] == "SP"]

In [75]:
df_estado_sp.to_csv("merged_uf_sp.csv", index=False)

In [76]:
df_estado_sp.to_json(
    "merged_uf_sp.json", orient="records", lines=True, force_ascii=False, indent=4
)

In [78]:
df_enem = pd.read_csv(
    "enem_data_ideb_filtrados_sp.csv", encoding="ISO-8859-1", sep=",", low_memory=False
)

In [79]:
df_enem.rename(
    columns={"CO_MUNICIPIO_ESC": "CO_ENTIDADE"},
    inplace=True,
)

In [80]:
df_estado_sp3 = pd.merge(
    df_estado_sp, df_enem[["CO_ENTIDADE", "IDEB_2023"]], on="CO_ENTIDADE", how="left"
)

In [81]:
df_estado_sp3.to_csv("merged_uf_sp_enem.csv", index=False)

In [82]:
df_estado_sp3.to_json(
    "merged_estado_sp_enem.json",
    orient="records",
    lines=True,
    force_ascii=False,
    indent=4,
)

In [85]:
df_estado_sp3

,NO_MUNICIPIO,NO_UF,SG_UF,CO_DISTRITO,NO_ENTIDADE,CO_ENTIDADE,longitude,latitude,DEPENDENCIA,ATIVIDADE,VÍNCULOS_PUBLICOS,MANTENEDOR_ESCOLA_PRIVADA,PREDIO_ESCOLAR,LOCAL_ESCOLAR,ABASTECIMENTO_AGUA,ABASTECIMENTO_ENERGIA,TAXA_DE_ACESSIBILIDADE,DS_ENDERECO,NU_ENDERECO,DS_COMPLEMENTO,NO_BAIRRO,CO_CEP,NU_DDD,NU_TELEFONE,ESGOTO,TAXA_DE_INFRAESTRUTURA,LISTA_INFRAESTRUTURAS,LISTA_PROFISSIONAIS,IDEB_2023
0,São Paulo,São Paulo,SP,355030840,AYRES DE MOURA PROFESSOR,35000012,-46.749710,-23.512270,Estadual,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,1,RUA ARTUR ORLANDO,907,RUA,VILA JAGUARA,5118000,11.0,36251934.0,Rede pública,4,"[Laboratório de Ciências, Laboratório de Infor...",[],NaN
1,São Paulo,São Paulo,SP,355030861,GAVIAO PEIXOTO BRIGADEIRO,35000024,-46.759380,-23.404710,Estadual,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,0,MOGEIRO,710,RUA,VILA PERUS,5208230,11.0,39170748.0,Rede pública,2,"[Laboratório de Informática, Quadra de Esportes]",[],-
2,São Paulo,São Paulo,SP,355030829,JOAO SOLIMEO,35000036,-46.698399,-23.469469,Estadual,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,0,DO SABAO,1497,ESTRADA,JARDIM MARISTELA,2806000,11.0,39238001.0,Rede pública,3,"[Laboratório de Informática, Quadra de Esporte...",[],-
3,São Paulo,São Paulo,SP,355030811,WALFREDO ARANTES CALDAS PROFESSOR,35000048,-46.679710,-23.464000,Estadual,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,0,DEPUTADO CANTIDIO SAMPAIO,1701,NaN,VILA SOUZA,2860001,NaN,NaN,Rede pública,2,"[Laboratório de Informática, Quadra de Esportes]",[],-
4,São Paulo,São Paulo,SP,355030803,SEBASTIAO DE OLIVEIRA GUSMAO PROFESSOR,35000059,-46.792447,-23.438346,Estadual,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,0,RUA FRANCISCO GIRON,SN,ESTRADA,MORRO DOCE,5267000,11.0,39166331.0,Rede pública,3,"[Laboratório de Ciências, Laboratório de Infor...",[],"3,8"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34094,Santa Fé do Sul,São Paulo,SP,354660305,CEL JTO A EE ITAEL DE MATOS PROFESSOR,35985806,-50.923018,-20.208689,Estadual,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,1,RUA OITO,764,RUA,CENTRO,15775000,17.0,36310848.0,Rede pública,2,"[Laboratório de Ciências, Laboratório de Infor...",[],NaN
34095,Franca,São Paulo,SP,351620005,CEL JTO A EE TORQUATO CALEIRO,35985818,-47.399068,-20.532132,Estadual,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,0,RUA LIBERO BADARO,1150,RUA,CENTRO,14400570,16.0,37223343.0,Rede pública,4,"[Laboratório de Ciências, Laboratório de Infor...",[],NaN
34096,Fernandópolis,São Paulo,SP,351550905,CEL JTO A EE JOAQUIM ANTONIO PEREIRA,35985824,-50.252814,-20.282983,Estadual,Paralisada,Não,Empresa do setor privado,Indefinido,Outros,Não há abastecimento de água,Não há energia elétrica,0,AVENIDA DOS ARNALDOS,1342,AVENIDA,CENTRO,15600028,17.0,34628118.0,Não há tratamento de esgoto,0,[],[],NaN
34097,Igaraçu do Tietê,São Paulo,SP,352000405,CEL JTO A EE JOSE CONTI,35985831,-48.562420,-22.510167,Estadual,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Prédio compartilhado com outra escola,Rede pública,Rede pública,0,AVENIDA JOSE MICHEL MUCARE,801,NaN,JARDIM NOVO ESTILO,17350298,14.0,36441777.0,Rede pública,1,[Laboratório de Informática],[],NaN
34098,São Paulo,São Paulo,SP,355030856,IFSP - CAMPUS SAO PAULO,35990012,-46.621687,-23.523877,Federal,Em atividade,Secretaria de Educação,Empresa do setor privado,Próprio,Outros,Rede pública,Rede pública,5,RUA PEDRO VICENTE,625,NaN,PARI,1109010,11.0,27632664.0,Rede pública,8,"[Área Verde, Biblioteca, Laboratório de Ciênci...","[Nutricionista, Psicólogo, Segurança/Guarda, T...",-